properties:
  template:
    volumes:
      - name: data-volume
        storageType: AzureFile
        storageName: depot-data-storage
    containers:
      - name: depot-butler-job
        volumeMounts:
          - volumeName: data-volume
            mountPath: /mnt/data
